title: POLITIX Docs  
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://shiyis.github.io

aux_links:
  Template Repository: https://github.com/shiyis/politix-docs
